import "./globals.css";
import { Exo_2, } from "next/font/google";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import NextAuthSessionProvider from "@/Providers/NextAuthProvider";

// configure font
const exoFont = Exo_2({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // add the weights you need
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${exoFont.className}`}>
      <NextAuthSessionProvider>
        <body>
          <Navbar />
          <main>
            {children}
          </main>
          <Footer />
        </body>
      </NextAuthSessionProvider>
    </html>
  );
}
